// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [CreateMicrosoftAdDomain][google.cloud.managedidentities.v1.CreateMicrosoftAdDomain]
public struct CreateMicrosoftAdDomainRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource project name and location using the form:
  /// `projects/{project_id}/locations/global`
  public var parent: Swift.String = Swift.String()

  /// Required. The fully qualified domain name.
  /// e.g. mydomain.myorganization.com, with the following restrictions:
  ///
  ///  * Must contain only lowercase letters, numbers, periods and hyphens.
  ///  * Must start with a letter.
  ///  * Must contain between 2-64 characters.
  ///  * Must end with a number or a letter.
  ///  * Must not start with period.
  ///  * First segement length (mydomain form example above) shouldn't exceed
  ///    15 chars.
  ///  * The last segment cannot be fully numeric.
  ///  * Must be unique within the customer project.
  public var domainName: Swift.String = Swift.String()

  /// Required. A Managed Identity domain resource.
  public var domain: Domain? = nil

  /// Initialize a new instance of `CreateMicrosoftAdDomainRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateMicrosoftAdDomainRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.managedidentities.v1.CreateMicrosoftAdDomainRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
