// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Represents a managed Microsoft Active Directory domain.
public struct Domain: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The unique name of the domain using the form:
  /// `projects/{project_id}/locations/global/domains/{domain_name}`.
  public var name: Swift.String = Swift.String()

  /// Optional. Resource labels that can contain user-provided metadata.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. The full names of the Google Compute Engine
  /// [networks](/compute/docs/networks-and-firewalls#networks) the domain
  /// instance is connected to. Networks can be added using UpdateDomain.
  /// The domain is only available on networks listed in `authorized_networks`.
  /// If CIDR subnets overlap between networks, domain creation will fail.
  public var authorizedNetworks: [Swift.String] = []

  /// Required. The CIDR range of internal addresses that are reserved for this
  /// domain. Reserved networks must be /24 or larger. Ranges must be
  /// unique and non-overlapping with existing subnets in
  /// [Domain].[authorized_networks].
  public var reservedIpRange: Swift.String = Swift.String()

  /// Required. Locations where domain needs to be provisioned.
  /// [regions][compute/docs/regions-zones/]
  /// e.g. us-west1 or us-east4
  /// Service supports up to 4 locations at once. Each location will use a /26
  /// block.
  public var locations: [Swift.String] = []

  /// Optional. The name of delegated administrator account used to perform
  /// Active Directory operations. If not specified, `setupadmin` will be used.
  public var admin: Swift.String = Swift.String()

  /// Output only. The fully-qualified domain name of the exposed domain used by
  /// clients to connect to the service. Similar to what would be chosen for an
  /// Active Directory set up on an internal network.
  public var fqdn: Swift.String = Swift.String()

  /// Output only. The time the instance was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The last update time.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The current state of this domain.
  public var state: Domain.State = Domain.State()

  /// Output only. Additional information about the current status of this
  /// domain, if available.
  public var statusMessage: Swift.String = Swift.String()

  /// Output only. The current trusts associated with the domain.
  public var trusts: [Trust] = []

  /// Initialize a new instance of `Domain`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Domain().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Represents the different states of a managed domain.
  public enum State: Codable, Equatable, Sendable {
    /// Not set.
    case unspecified
    /// The domain is being created.
    case creating
    /// The domain has been created and is fully usable.
    case ready
    /// The domain's configuration is being updated.
    case updating
    /// The domain is being deleted.
    case deleting
    /// The domain is being repaired and may be unusable. Details
    /// can be found in the `status_message` field.
    case repairing
    /// The domain is undergoing maintenance.
    case performingMaintenance
    /// The domain is not serving requests.
    case unavailable
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .ready: return 2
      case .updating: return 3
      case .deleting: return 4
      case .repairing: return 5
      case .performingMaintenance: return 6
      case .unavailable: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .ready: return "READY"
      case .updating: return "UPDATING"
      case .deleting: return "DELETING"
      case .repairing: return "REPAIRING"
      case .performingMaintenance: return "PERFORMING_MAINTENANCE"
      case .unavailable: return "UNAVAILABLE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "READY": self = .ready
      case "UPDATING": self = .updating
      case "DELETING": self = .deleting
      case "REPAIRING": self = .repairing
      case "PERFORMING_MAINTENANCE": self = .performingMaintenance
      case "UNAVAILABLE": self = .unavailable
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .ready
      case 3: self = .updating
      case 4: self = .deleting
      case 5: self = .repairing
      case 6: self = .performingMaintenance
      case 7: self = .unavailable
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .creating: return try container.encode(1)
      case .ready: return try container.encode(2)
      case .updating: return try container.encode(3)
      case .deleting: return try container.encode(4)
      case .repairing: return try container.encode(5)
      case .performingMaintenance: return try container.encode(6)
      case .unavailable: return try container.encode(7)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.managedidentities.v1.Domain"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
