// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [ListDomains][google.cloud.managedidentities.v1.ListDomains]
public struct ListDomainsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name of the domain location using the form:
  /// `projects/{project_id}/locations/global`
  public var parent: Swift.String = Swift.String()

  /// Optional. The maximum number of items to return.
  /// If not specified, a default value of 1000 will be used.
  /// Regardless of the page_size value, the response may include a partial list.
  /// Callers should rely on a response's
  /// [next_page_token][google.cloud.managedidentities.v1.ListDomainsResponse.next_page_token]
  /// to determine if there are additional results to list.
  ///
  /// [google.cloud.managedidentities.v1.ListDomainsResponse.next_page_token]: <doc:ListDomainsResponse/nextPageToken>
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. The `next_page_token` value returned from a previous ListDomainsRequest
  /// request, if any.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. A filter specifying constraints of a list operation.
  /// For example, `Domain.fqdn="mydomain.myorginization"`.
  public var filter: Swift.String = Swift.String()

  /// Optional. Specifies the ordering of results. See
  /// [Sorting
  /// order](https://cloud.google.com/apis/design/design_patterns#sorting_order)
  /// for more information.
  public var orderBy: Swift.String = Swift.String()

  /// Initialize a new instance of `ListDomainsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListDomainsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.managedidentities.v1.ListDomainsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
