// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message for
/// [ListDomains][google.cloud.managedidentities.v1.ListDomains]
public struct ListDomainsRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of the domain location using the form:
  /// `projects/{project_id}/locations/global`
  public var parent: Swift.String = Swift.String()

  /// Optional. The maximum number of items to return.
  /// If not specified, a default value of 1000 will be used.
  /// Regardless of the page_size value, the response may include a partial list.
  /// Callers should rely on a response's
  /// [next_page_token][google.cloud.managedidentities.v1.ListDomainsResponse.next_page_token]
  /// to determine if there are additional results to list.
  ///
  /// [google.cloud.managedidentities.v1.ListDomainsResponse.next_page_token]: <doc:ListDomainsResponse/nextPageToken>
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. The `next_page_token` value returned from a previous ListDomainsRequest
  /// request, if any.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. A filter specifying constraints of a list operation.
  /// For example, `Domain.fqdn="mydomain.myorginization"`.
  public var filter: Swift.String = Swift.String()

  /// Optional. Specifies the ordering of results. See
  /// [Sorting
  /// order](https://cloud.google.com/apis/design/design_patterns#sorting_order)
  /// for more information.
  public var orderBy: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `ListDomainsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListDomainsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let pageSize = CodingKeys(stringValue: "pageSize")
    static let pageToken = CodingKeys(stringValue: "pageToken")
    static let filter = CodingKeys(stringValue: "filter")
    static let orderBy = CodingKeys(stringValue: "orderBy")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "pageSize",
      "pageToken",
      "filter",
      "orderBy",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .pageSize) {
      self.pageSize = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pageToken) {
      self.pageToken = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .filter) {
      self.filter = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .orderBy) {
      self.orderBy = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.pageSize, forKey: .pageSize)
    try container.encode(self.pageToken, forKey: .pageToken)
    try container.encode(self.filter, forKey: .filter)
    try container.encode(self.orderBy, forKey: .orderBy)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.managedidentities.v1.ListDomainsRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
