// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class ManagedIdentitiesServiceLogging: ManagedIdentitiesServiceStub {
    let inner: any ManagedIdentitiesServiceStub
    let logger: Logger

    public init(_ inner: any ManagedIdentitiesServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-managedidentities-v1"
      logger[metadataKey: "gcp.client.service"] = "managedidentities"
      logger[metadataKey: "gcp.experimental.swift.client"] = "ManagedIdentitiesService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func createMicrosoftAdDomain(
      request: CreateMicrosoftAdDomainRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createMicrosoftAdDomain",
        action: {
          (r: CreateMicrosoftAdDomainRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createMicrosoftAdDomain(request: r, options: o)
        })
    }

    public func resetAdminPassword(
      request: ResetAdminPasswordRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudManagedIdentitiesV1.ResetAdminPasswordResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "resetAdminPassword",
        action: {
          (r: ResetAdminPasswordRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudManagedIdentitiesV1.ResetAdminPasswordResponse
          in
          return try await self.inner.resetAdminPassword(request: r, options: o)
        })
    }

    public func listDomains(
      request: ListDomainsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudManagedIdentitiesV1.ListDomainsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listDomains",
        action: {
          (r: ListDomainsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudManagedIdentitiesV1.ListDomainsResponse
          in
          return try await self.inner.listDomains(request: r, options: o)
        })
    }

    public func getDomain(
      request: GetDomainRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudManagedIdentitiesV1.Domain {
      try await self._intercept(
        request: request,
        options: options,
        name: "getDomain",
        action: {
          (r: GetDomainRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudManagedIdentitiesV1.Domain
          in
          return try await self.inner.getDomain(request: r, options: o)
        })
    }

    public func updateDomain(
      request: UpdateDomainRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateDomain",
        action: {
          (r: UpdateDomainRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateDomain(request: r, options: o)
        })
    }

    public func deleteDomain(
      request: DeleteDomainRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteDomain",
        action: {
          (r: DeleteDomainRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteDomain(request: r, options: o)
        })
    }

    public func attachTrust(
      request: AttachTrustRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "attachTrust",
        action: {
          (r: AttachTrustRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.attachTrust(request: r, options: o)
        })
    }

    public func reconfigureTrust(
      request: ReconfigureTrustRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "reconfigureTrust",
        action: {
          (r: ReconfigureTrustRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.reconfigureTrust(request: r, options: o)
        })
    }

    public func detachTrust(
      request: DetachTrustRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "detachTrust",
        action: {
          (r: DetachTrustRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.detachTrust(request: r, options: o)
        })
    }

    public func validateTrust(
      request: ValidateTrustRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "validateTrust",
        action: {
          (r: ValidateTrustRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.validateTrust(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
