// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// API Overview
///
/// The `managedidentites.googleapis.com` service implements the Google Cloud
/// Managed Identites API for identity services
/// (e.g. Microsoft Active Directory).
///
/// The Managed Identities service provides methods to manage
/// (create/read/update/delete) domains, reset managed identities admin password,
/// add/remove domain controllers in GCP regions and add/remove VPC peering.
///
/// Data Model
///
/// The Managed Identities service exposes the following resources:
///
/// * Locations as global, named as follows:
///   `projects/{project_id}/locations/global`.
///
/// * Domains, named as follows:
///   `/projects/{project_id}/locations/global/domain/{domain_name}`.
///
/// The `{domain_name}` refers to fully qualified domain name in the customer
/// project e.g. mydomain.myorganization.com, with the following restrictions:
///
///  * Must contain only lowercase letters, numbers, periods and hyphens.
///  * Must start with a letter.
///  * Must contain between 2-64 characters.
///  * Must end with a number or a letter.
///  * Must not start with period.
///  * First segement length (mydomain form example above) shouldn't exceed
///    15 chars.
///  * The last segment cannot be fully numeric.
///  * Must be unique within the customer project.
///
/// @Snippet(path: "ManagedIdentitiesServiceQuickstart")
public class ManagedIdentitiesServiceClient: Clients.ManagedIdentitiesServiceProtocol {
  let inner: any Clients.ManagedIdentitiesServiceStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `ManagedIdentitiesServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.ManagedIdentitiesServiceStub =
      try Clients.ManagedIdentitiesServiceTransport(options)
    inner = Clients.ManagedIdentitiesServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ManagedIdentitiesServiceLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Creates a Microsoft AD domain.
  ///
  /// @Snippet(path: "ManagedIdentitiesService_CreateMicrosoftAdDomain")
  public func createMicrosoftAdDomain(
    request: CreateMicrosoftAdDomainRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createMicrosoftAdDomain(request: request, options: options)
  }

  /// Creates a Microsoft AD domain.
  ///
  /// @Snippet(path: "ManagedIdentitiesService_CreateMicrosoftAdDomain")
  public func createMicrosoftAdDomain(
    withPolling: CreateMicrosoftAdDomainRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Domain> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Domain>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Domain(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.createMicrosoftAdDomain(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Domain>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Resets a domain's administrator password.
  ///
  /// @Snippet(path: "ManagedIdentitiesService_ResetAdminPassword")
  public func resetAdminPassword(
    request: ResetAdminPasswordRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedIdentitiesV1.ResetAdminPasswordResponse {
    try await self.inner.resetAdminPassword(request: request, options: options)
  }

  /// Lists domains in a project.
  ///
  /// @Snippet(path: "ManagedIdentitiesService_ListDomains")
  public func listDomains(
    request: ListDomainsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedIdentitiesV1.ListDomainsResponse {
    try await self.inner.listDomains(request: request, options: options)
  }

  /// Lists domains in a project.
  ///
  /// @Snippet(path: "ManagedIdentitiesService_ListDomains")
  public func listDomains(
    byItem: ListDomainsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Domain, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudManagedIdentitiesV1.ListDomainsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listDomains(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a domain.
  ///
  /// @Snippet(path: "ManagedIdentitiesService_GetDomain")
  public func getDomain(
    request: GetDomainRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedIdentitiesV1.Domain {
    try await self.inner.getDomain(request: request, options: options)
  }

  /// Updates the metadata and configuration of a domain.
  ///
  /// @Snippet(path: "ManagedIdentitiesService_UpdateDomain")
  public func updateDomain(
    request: UpdateDomainRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateDomain(request: request, options: options)
  }

  /// Updates the metadata and configuration of a domain.
  ///
  /// @Snippet(path: "ManagedIdentitiesService_UpdateDomain")
  public func updateDomain(
    withPolling: UpdateDomainRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Domain> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Domain>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Domain(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.updateDomain(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Domain>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a domain.
  ///
  /// @Snippet(path: "ManagedIdentitiesService_DeleteDomain")
  public func deleteDomain(
    request: DeleteDomainRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteDomain(request: request, options: options)
  }

  /// Deletes a domain.
  ///
  /// @Snippet(path: "ManagedIdentitiesService_DeleteDomain")
  public func deleteDomain(
    withPolling: DeleteDomainRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Void>.State
      in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response:
        return .init(done: true, result: .success(()))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.deleteDomain(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Adds an AD trust to a domain.
  ///
  /// @Snippet(path: "ManagedIdentitiesService_AttachTrust")
  public func attachTrust(
    request: AttachTrustRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.attachTrust(request: request, options: options)
  }

  /// Adds an AD trust to a domain.
  ///
  /// @Snippet(path: "ManagedIdentitiesService_AttachTrust")
  public func attachTrust(
    withPolling: AttachTrustRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Domain> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Domain>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Domain(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.attachTrust(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Domain>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the DNS conditional forwarder.
  ///
  /// @Snippet(path: "ManagedIdentitiesService_ReconfigureTrust")
  public func reconfigureTrust(
    request: ReconfigureTrustRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.reconfigureTrust(request: request, options: options)
  }

  /// Updates the DNS conditional forwarder.
  ///
  /// @Snippet(path: "ManagedIdentitiesService_ReconfigureTrust")
  public func reconfigureTrust(
    withPolling: ReconfigureTrustRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Domain> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Domain>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Domain(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.reconfigureTrust(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Domain>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Removes an AD trust.
  ///
  /// @Snippet(path: "ManagedIdentitiesService_DetachTrust")
  public func detachTrust(
    request: DetachTrustRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.detachTrust(request: request, options: options)
  }

  /// Removes an AD trust.
  ///
  /// @Snippet(path: "ManagedIdentitiesService_DetachTrust")
  public func detachTrust(
    withPolling: DetachTrustRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Domain> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Domain>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Domain(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.detachTrust(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Domain>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Validates a trust state, that the target domain is reachable, and that the
  /// target domain is able to accept incoming trust requests.
  ///
  /// @Snippet(path: "ManagedIdentitiesService_ValidateTrust")
  public func validateTrust(
    request: ValidateTrustRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.validateTrust(request: request, options: options)
  }

  /// Validates a trust state, that the target domain is reachable, and that the
  /// target domain is able to accept incoming trust requests.
  ///
  /// @Snippet(path: "ManagedIdentitiesService_ValidateTrust")
  public func validateTrust(
    withPolling: ValidateTrustRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Domain> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Domain>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Domain(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.validateTrust(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Domain>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "ManagedIdentitiesService_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "ManagedIdentitiesService_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "ManagedIdentitiesService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "ManagedIdentitiesService_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "ManagedIdentitiesService_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ManagedIdentitiesServiceClient`.
  ///
  /// To mock `ManagedIdentitiesServiceClient` change your functions to receive
  /// `some ManagedIdentitiesServiceProtocol` or `any ManagedIdentitiesServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ManagedIdentitiesServiceProtocol {
    /// See `ManagedIdentitiesServiceClient.createMicrosoftAdDomain`.
    func createMicrosoftAdDomain(request: CreateMicrosoftAdDomainRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `ManagedIdentitiesServiceClient.createMicrosoftAdDomain`.
    func createMicrosoftAdDomain(withPolling: CreateMicrosoftAdDomainRequest) async throws
      -> any GoogleCloudGax.PollableOperation<Domain>

    /// See `ManagedIdentitiesServiceClient.createMicrosoftAdDomain`.
    func createMicrosoftAdDomain(
      parent: Swift.String,
      domainName: Swift.String,
      domain: Domain?,
    ) async throws -> any GoogleCloudGax.PollableOperation<Domain>

    /// See `ManagedIdentitiesServiceClient.resetAdminPassword`.
    func resetAdminPassword(request: ResetAdminPasswordRequest) async throws
      -> GoogleCloudManagedIdentitiesV1.ResetAdminPasswordResponse

    /// See `ManagedIdentitiesServiceClient.resetAdminPassword`.
    func resetAdminPassword(
      name: Swift.String,
    ) async throws -> GoogleCloudManagedIdentitiesV1.ResetAdminPasswordResponse

    /// See `ManagedIdentitiesServiceClient.listDomains`.
    func listDomains(request: ListDomainsRequest) async throws
      -> GoogleCloudManagedIdentitiesV1.ListDomainsResponse

    /// See `ManagedIdentitiesServiceClient.listDomains`.
    func listDomains(
      byItem: ListDomainsRequest
    ) throws -> any AsyncSequence<Domain, Swift.Error>

    /// See `ManagedIdentitiesServiceClient.listDomains`.
    func listDomains(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Domain, Swift.Error>

    /// See `ManagedIdentitiesServiceClient.getDomain`.
    func getDomain(request: GetDomainRequest) async throws -> GoogleCloudManagedIdentitiesV1.Domain

    /// See `ManagedIdentitiesServiceClient.getDomain`.
    func getDomain(
      name: Swift.String,
    ) async throws -> GoogleCloudManagedIdentitiesV1.Domain

    /// See `ManagedIdentitiesServiceClient.updateDomain`.
    func updateDomain(request: UpdateDomainRequest) async throws -> GoogleLongRunning.Operation

    /// See `ManagedIdentitiesServiceClient.updateDomain`.
    func updateDomain(withPolling: UpdateDomainRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Domain>

    /// See `ManagedIdentitiesServiceClient.updateDomain`.
    func updateDomain(
      domain: Domain?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<Domain>

    /// See `ManagedIdentitiesServiceClient.deleteDomain`.
    func deleteDomain(request: DeleteDomainRequest) async throws -> GoogleLongRunning.Operation

    /// See `ManagedIdentitiesServiceClient.deleteDomain`.
    func deleteDomain(withPolling: DeleteDomainRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Void>

    /// See `ManagedIdentitiesServiceClient.deleteDomain`.
    func deleteDomain(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `ManagedIdentitiesServiceClient.attachTrust`.
    func attachTrust(request: AttachTrustRequest) async throws -> GoogleLongRunning.Operation

    /// See `ManagedIdentitiesServiceClient.attachTrust`.
    func attachTrust(withPolling: AttachTrustRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Domain>

    /// See `ManagedIdentitiesServiceClient.attachTrust`.
    func attachTrust(
      name: Swift.String,
      trust: Trust?,
    ) async throws -> any GoogleCloudGax.PollableOperation<Domain>

    /// See `ManagedIdentitiesServiceClient.reconfigureTrust`.
    func reconfigureTrust(request: ReconfigureTrustRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `ManagedIdentitiesServiceClient.reconfigureTrust`.
    func reconfigureTrust(withPolling: ReconfigureTrustRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Domain>

    /// See `ManagedIdentitiesServiceClient.reconfigureTrust`.
    func reconfigureTrust(
      name: Swift.String,
      targetDomainName: Swift.String,
      targetDnsIpAddresses: [Swift.String],
    ) async throws -> any GoogleCloudGax.PollableOperation<Domain>

    /// See `ManagedIdentitiesServiceClient.detachTrust`.
    func detachTrust(request: DetachTrustRequest) async throws -> GoogleLongRunning.Operation

    /// See `ManagedIdentitiesServiceClient.detachTrust`.
    func detachTrust(withPolling: DetachTrustRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Domain>

    /// See `ManagedIdentitiesServiceClient.detachTrust`.
    func detachTrust(
      name: Swift.String,
      trust: Trust?,
    ) async throws -> any GoogleCloudGax.PollableOperation<Domain>

    /// See `ManagedIdentitiesServiceClient.validateTrust`.
    func validateTrust(request: ValidateTrustRequest) async throws -> GoogleLongRunning.Operation

    /// See `ManagedIdentitiesServiceClient.validateTrust`.
    func validateTrust(withPolling: ValidateTrustRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Domain>

    /// See `ManagedIdentitiesServiceClient.validateTrust`.
    func validateTrust(
      name: Swift.String,
      trust: Trust?,
    ) async throws -> any GoogleCloudGax.PollableOperation<Domain>

    /// See `ManagedIdentitiesServiceClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `ManagedIdentitiesServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `ManagedIdentitiesServiceClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `ManagedIdentitiesServiceClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `ManagedIdentitiesServiceClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `ManagedIdentitiesServiceClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `ManagedIdentitiesServiceClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `ManagedIdentitiesServiceClient.createMicrosoftAdDomain`.
    func createMicrosoftAdDomain(
      request: CreateMicrosoftAdDomainRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ManagedIdentitiesServiceClient.createMicrosoftAdDomain`.
    func createMicrosoftAdDomain(
      withPolling: CreateMicrosoftAdDomainRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Domain>

    /// See `ManagedIdentitiesServiceClient.resetAdminPassword`.
    func resetAdminPassword(
      request: ResetAdminPasswordRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedIdentitiesV1.ResetAdminPasswordResponse

    /// See `ManagedIdentitiesServiceClient.listDomains`.
    func listDomains(
      request: ListDomainsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedIdentitiesV1.ListDomainsResponse

    /// See `ManagedIdentitiesServiceClient.listDomains`.
    func listDomains(
      byItem: ListDomainsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Domain, Swift.Error>

    /// See `ManagedIdentitiesServiceClient.getDomain`.
    func getDomain(
      request: GetDomainRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedIdentitiesV1.Domain

    /// See `ManagedIdentitiesServiceClient.updateDomain`.
    func updateDomain(
      request: UpdateDomainRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ManagedIdentitiesServiceClient.updateDomain`.
    func updateDomain(
      withPolling: UpdateDomainRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Domain>

    /// See `ManagedIdentitiesServiceClient.deleteDomain`.
    func deleteDomain(
      request: DeleteDomainRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ManagedIdentitiesServiceClient.deleteDomain`.
    func deleteDomain(
      withPolling: DeleteDomainRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `ManagedIdentitiesServiceClient.attachTrust`.
    func attachTrust(
      request: AttachTrustRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ManagedIdentitiesServiceClient.attachTrust`.
    func attachTrust(
      withPolling: AttachTrustRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Domain>

    /// See `ManagedIdentitiesServiceClient.reconfigureTrust`.
    func reconfigureTrust(
      request: ReconfigureTrustRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ManagedIdentitiesServiceClient.reconfigureTrust`.
    func reconfigureTrust(
      withPolling: ReconfigureTrustRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Domain>

    /// See `ManagedIdentitiesServiceClient.detachTrust`.
    func detachTrust(
      request: DetachTrustRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ManagedIdentitiesServiceClient.detachTrust`.
    func detachTrust(
      withPolling: DetachTrustRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Domain>

    /// See `ManagedIdentitiesServiceClient.validateTrust`.
    func validateTrust(
      request: ValidateTrustRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ManagedIdentitiesServiceClient.validateTrust`.
    func validateTrust(
      withPolling: ValidateTrustRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Domain>

    /// See `ManagedIdentitiesServiceClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `ManagedIdentitiesServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `ManagedIdentitiesServiceClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `ManagedIdentitiesServiceClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.ManagedIdentitiesServiceProtocol {
  public func createMicrosoftAdDomain(request: CreateMicrosoftAdDomainRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createMicrosoftAdDomain(request: request, options: .init())
  }

  public func createMicrosoftAdDomain(
    request: CreateMicrosoftAdDomainRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createMicrosoftAdDomain(withPolling: CreateMicrosoftAdDomainRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Domain>
  {
    try await self.createMicrosoftAdDomain(withPolling: withPolling, options: .init())
  }

  public func createMicrosoftAdDomain(
    withPolling: CreateMicrosoftAdDomainRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Domain> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Domain>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createMicrosoftAdDomain(
    parent: Swift.String,
    domainName: Swift.String,
    domain: Domain?,
  ) async throws -> any GoogleCloudGax.PollableOperation<Domain> {
    let request = CreateMicrosoftAdDomainRequest().with {
      $0.parent = parent
      $0.domainName = domainName
      $0.domain = domain
    }
    return try await self.createMicrosoftAdDomain(withPolling: request)
  }

  public func resetAdminPassword(request: ResetAdminPasswordRequest) async throws
    -> GoogleCloudManagedIdentitiesV1.ResetAdminPasswordResponse
  {
    try await self.resetAdminPassword(request: request, options: .init())
  }

  public func resetAdminPassword(
    request: ResetAdminPasswordRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedIdentitiesV1.ResetAdminPasswordResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func resetAdminPassword(
    name: Swift.String,
  ) async throws -> GoogleCloudManagedIdentitiesV1.ResetAdminPasswordResponse {
    let request = ResetAdminPasswordRequest().with {
      $0.name = name
    }
    return try await self.resetAdminPassword(request: request)
  }

  public func listDomains(request: ListDomainsRequest) async throws
    -> GoogleCloudManagedIdentitiesV1.ListDomainsResponse
  {
    try await self.listDomains(request: request, options: .init())
  }

  public func listDomains(
    request: ListDomainsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedIdentitiesV1.ListDomainsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listDomains(
    byItem: ListDomainsRequest
  ) throws -> any AsyncSequence<Domain, Swift.Error> {
    try self.listDomains(byItem: byItem, options: .init())
  }

  public func listDomains(
    byItem: ListDomainsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Domain, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudManagedIdentitiesV1.ListDomainsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listDomains(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Domain, Swift.Error> {
    let request = ListDomainsRequest().with {
      $0.parent = parent
    }
    return try self.listDomains(byItem: request)
  }

  public func getDomain(request: GetDomainRequest) async throws
    -> GoogleCloudManagedIdentitiesV1.Domain
  {
    try await self.getDomain(request: request, options: .init())
  }

  public func getDomain(
    request: GetDomainRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedIdentitiesV1.Domain {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getDomain(
    name: Swift.String,
  ) async throws -> GoogleCloudManagedIdentitiesV1.Domain {
    let request = GetDomainRequest().with {
      $0.name = name
    }
    return try await self.getDomain(request: request)
  }

  public func updateDomain(request: UpdateDomainRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.updateDomain(request: request, options: .init())
  }

  public func updateDomain(
    request: UpdateDomainRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateDomain(withPolling: UpdateDomainRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Domain>
  {
    try await self.updateDomain(withPolling: withPolling, options: .init())
  }

  public func updateDomain(
    withPolling: UpdateDomainRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Domain> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Domain>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateDomain(
    domain: Domain?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<Domain> {
    let request = UpdateDomainRequest().with {
      $0.domain = domain
      $0.updateMask = updateMask
    }
    return try await self.updateDomain(withPolling: request)
  }

  public func deleteDomain(request: DeleteDomainRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.deleteDomain(request: request, options: .init())
  }

  public func deleteDomain(
    request: DeleteDomainRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteDomain(withPolling: DeleteDomainRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Void>
  {
    try await self.deleteDomain(withPolling: withPolling, options: .init())
  }

  public func deleteDomain(
    withPolling: DeleteDomainRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteDomain(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let request = DeleteDomainRequest().with {
      $0.name = name
    }
    return try await self.deleteDomain(withPolling: request)
  }

  public func attachTrust(request: AttachTrustRequest) async throws -> GoogleLongRunning.Operation {
    try await self.attachTrust(request: request, options: .init())
  }

  public func attachTrust(
    request: AttachTrustRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func attachTrust(withPolling: AttachTrustRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Domain>
  {
    try await self.attachTrust(withPolling: withPolling, options: .init())
  }

  public func attachTrust(
    withPolling: AttachTrustRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Domain> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Domain>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func attachTrust(
    name: Swift.String,
    trust: Trust?,
  ) async throws -> any GoogleCloudGax.PollableOperation<Domain> {
    let request = AttachTrustRequest().with {
      $0.name = name
      $0.trust = trust
    }
    return try await self.attachTrust(withPolling: request)
  }

  public func reconfigureTrust(request: ReconfigureTrustRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.reconfigureTrust(request: request, options: .init())
  }

  public func reconfigureTrust(
    request: ReconfigureTrustRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func reconfigureTrust(withPolling: ReconfigureTrustRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Domain>
  {
    try await self.reconfigureTrust(withPolling: withPolling, options: .init())
  }

  public func reconfigureTrust(
    withPolling: ReconfigureTrustRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Domain> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Domain>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func reconfigureTrust(
    name: Swift.String,
    targetDomainName: Swift.String,
    targetDnsIpAddresses: [Swift.String],
  ) async throws -> any GoogleCloudGax.PollableOperation<Domain> {
    let request = ReconfigureTrustRequest().with {
      $0.name = name
      $0.targetDomainName = targetDomainName
      $0.targetDnsIpAddresses = targetDnsIpAddresses
    }
    return try await self.reconfigureTrust(withPolling: request)
  }

  public func detachTrust(request: DetachTrustRequest) async throws -> GoogleLongRunning.Operation {
    try await self.detachTrust(request: request, options: .init())
  }

  public func detachTrust(
    request: DetachTrustRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func detachTrust(withPolling: DetachTrustRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Domain>
  {
    try await self.detachTrust(withPolling: withPolling, options: .init())
  }

  public func detachTrust(
    withPolling: DetachTrustRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Domain> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Domain>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func detachTrust(
    name: Swift.String,
    trust: Trust?,
  ) async throws -> any GoogleCloudGax.PollableOperation<Domain> {
    let request = DetachTrustRequest().with {
      $0.name = name
      $0.trust = trust
    }
    return try await self.detachTrust(withPolling: request)
  }

  public func validateTrust(request: ValidateTrustRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.validateTrust(request: request, options: .init())
  }

  public func validateTrust(
    request: ValidateTrustRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func validateTrust(withPolling: ValidateTrustRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Domain>
  {
    try await self.validateTrust(withPolling: withPolling, options: .init())
  }

  public func validateTrust(
    withPolling: ValidateTrustRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Domain> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Domain>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func validateTrust(
    name: Swift.String,
    trust: Trust?,
  ) async throws -> any GoogleCloudGax.PollableOperation<Domain> {
    let request = ValidateTrustRequest().with {
      $0.name = name
      $0.trust = trust
    }
    return try await self.validateTrust(withPolling: request)
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
