// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Represents a relationship between two domains. This allows a controller in
/// one domain to authenticate a user in another domain.
public struct Trust: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The fully qualified target domain name which will be in trust with the
  /// current domain.
  public var targetDomainName: Swift.String = Swift.String()

  /// Required. The type of trust represented by the trust resource.
  public var trustType: Trust.TrustType = Trust.TrustType()

  /// Required. The trust direction, which decides if the current domain is trusted,
  /// trusting, or both.
  public var trustDirection: Trust.TrustDirection = Trust.TrustDirection()

  /// Optional. The trust authentication type, which decides whether the trusted side has
  /// forest/domain wide access or selective access to an approved set of
  /// resources.
  public var selectiveAuthentication: Swift.Bool = Swift.Bool()

  /// Required. The target DNS server IP addresses which can resolve the remote domain
  /// involved in the trust.
  public var targetDnsIpAddresses: [Swift.String] = []

  /// Required. The trust secret used for the handshake with the target domain. This will
  /// not be stored.
  public var trustHandshakeSecret: Swift.String = Swift.String()

  /// Output only. The time the instance was created.
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Output only. The last update time.
  public var updateTime: GoogleWKT.Timestamp? = nil

  /// Output only. The current state of the trust.
  public var state: Trust.State = Trust.State()

  /// Output only. Additional information about the current state of the trust, if available.
  public var stateDescription: Swift.String = Swift.String()

  /// Output only. The last heartbeat time when the trust was known to be connected.
  public var lastTrustHeartbeatTime: GoogleWKT.Timestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Trust`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Trust().with { $0.targetDomainName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let targetDomainName = CodingKeys(stringValue: "targetDomainName")
    static let trustType = CodingKeys(stringValue: "trustType")
    static let trustDirection = CodingKeys(stringValue: "trustDirection")
    static let selectiveAuthentication = CodingKeys(stringValue: "selectiveAuthentication")
    static let targetDnsIpAddresses = CodingKeys(stringValue: "targetDnsIpAddresses")
    static let trustHandshakeSecret = CodingKeys(stringValue: "trustHandshakeSecret")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let state = CodingKeys(stringValue: "state")
    static let stateDescription = CodingKeys(stringValue: "stateDescription")
    static let lastTrustHeartbeatTime = CodingKeys(stringValue: "lastTrustHeartbeatTime")

    static let _knownKeys: Set<Swift.String> = [
      "targetDomainName",
      "trustType",
      "trustDirection",
      "selectiveAuthentication",
      "targetDnsIpAddresses",
      "trustHandshakeSecret",
      "createTime",
      "updateTime",
      "state",
      "stateDescription",
      "lastTrustHeartbeatTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .targetDomainName) {
      self.targetDomainName = value
    }
    if let value = try container.decodeIfPresent(Trust.TrustType.self, forKey: .trustType) {
      self.trustType = value
    }
    if let value = try container.decodeIfPresent(Trust.TrustDirection.self, forKey: .trustDirection)
    {
      self.trustDirection = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .selectiveAuthentication)
    {
      self.selectiveAuthentication = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .targetDnsIpAddresses)
    {
      self.targetDnsIpAddresses = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .trustHandshakeSecret) {
      self.trustHandshakeSecret = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Trust.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .stateDescription) {
      self.stateDescription = value
    }
    self.lastTrustHeartbeatTime = try container.decodeIfPresent(
      GoogleWKT.Timestamp.self, forKey: .lastTrustHeartbeatTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.targetDomainName, forKey: .targetDomainName)
    try container.encode(self.trustType, forKey: .trustType)
    try container.encode(self.trustDirection, forKey: .trustDirection)
    try container.encode(self.selectiveAuthentication, forKey: .selectiveAuthentication)
    try container.encode(self.targetDnsIpAddresses, forKey: .targetDnsIpAddresses)
    try container.encode(self.trustHandshakeSecret, forKey: .trustHandshakeSecret)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.stateDescription, forKey: .stateDescription)
    try container.encodeIfPresent(self.lastTrustHeartbeatTime, forKey: .lastTrustHeartbeatTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Represents the different states of a domain trust.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Sendable {
    /// Not set.
    case unspecified
    /// The domain trust is being created.
    case creating
    /// The domain trust is being updated.
    case updating
    /// The domain trust is being deleted.
    case deleting
    /// The domain trust is connected.
    case connected
    /// The domain trust is disconnected.
    case disconnected
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .updating: return 2
      case .deleting: return 3
      case .connected: return 4
      case .disconnected: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .updating: return "UPDATING"
      case .deleting: return "DELETING"
      case .connected: return "CONNECTED"
      case .disconnected: return "DISCONNECTED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "UPDATING": self = .updating
      case "DELETING": self = .deleting
      case "CONNECTED": self = .connected
      case "DISCONNECTED": self = .disconnected
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .updating
      case 3: self = .deleting
      case 4: self = .connected
      case 5: self = .disconnected
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .creating: return try container.encode("CREATING")
      case .updating: return try container.encode("UPDATING")
      case .deleting: return try container.encode("DELETING")
      case .connected: return try container.encode("CONNECTED")
      case .disconnected: return try container.encode("DISCONNECTED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Represents the different inter-forest trust types.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum TrustType: Codable, Equatable, Sendable {
    /// Not set.
    case unspecified
    /// The forest trust.
    case forest
    /// The external domain trust.
    case external
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .forest: return 1
      case .external: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TRUST_TYPE_UNSPECIFIED"
      case .forest: return "FOREST"
      case .external: return "EXTERNAL"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:TrustType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TRUST_TYPE_UNSPECIFIED": self = .unspecified
      case "FOREST": self = .forest
      case "EXTERNAL": self = .external
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:TrustType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .forest
      case 2: self = .external
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("TRUST_TYPE_UNSPECIFIED")
      case .forest: return try container.encode("FOREST")
      case .external: return try container.encode("EXTERNAL")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Represents the direction of trust.
  /// See
  /// [System.DirectoryServices.ActiveDirectory.TrustDirection](https://docs.microsoft.com/en-us/dotnet/api/system.directoryservices.activedirectory.trustdirection?view=netframework-4.7.2)
  /// for more information.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum TrustDirection: Codable, Equatable, Sendable {
    /// Not set.
    case unspecified
    /// The inbound direction represents the trusting side.
    case inbound
    /// The outboud direction represents the trusted side.
    case outbound
    /// The bidirectional direction represents the trusted / trusting side.
    case bidirectional
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .inbound: return 1
      case .outbound: return 2
      case .bidirectional: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TRUST_DIRECTION_UNSPECIFIED"
      case .inbound: return "INBOUND"
      case .outbound: return "OUTBOUND"
      case .bidirectional: return "BIDIRECTIONAL"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:TrustDirection/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TRUST_DIRECTION_UNSPECIFIED": self = .unspecified
      case "INBOUND": self = .inbound
      case "OUTBOUND": self = .outbound
      case "BIDIRECTIONAL": self = .bidirectional
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:TrustDirection/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .inbound
      case 2: self = .outbound
      case 3: self = .bidirectional
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("TRUST_DIRECTION_UNSPECIFIED")
      case .inbound: return try container.encode("INBOUND")
      case .outbound: return try container.encode("OUTBOUND")
      case .bidirectional: return try container.encode("BIDIRECTIONAL")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.managedidentities.v1.Trust"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
